/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultHisConfig } from '../models';
import { HisConfig } from '../models';
/**
 * HisApi - axios parameter creator
 * @export
 */
export const HisApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取历史数据库配置
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiHisGetHisConfigGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/his/getHisConfig`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 保存历史数据库配置
         * @param {HisConfig} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiHisUpdateHisConfigPost: async (body?: HisConfig, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/his/updateHisConfig`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HisApi - functional programming interface
 * @export
 */
export const HisApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取历史数据库配置
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiHisGetHisConfigGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultHisConfig>>> {
            const localVarAxiosArgs = await HisApiAxiosParamCreator(configuration).apiHisGetHisConfigGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 保存历史数据库配置
         * @param {HisConfig} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiHisUpdateHisConfigPost(body?: HisConfig, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await HisApiAxiosParamCreator(configuration).apiHisUpdateHisConfigPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * HisApi - factory interface
 * @export
 */
export const HisApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 获取历史数据库配置
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiHisGetHisConfigGet(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultHisConfig>> {
            return HisApiFp(configuration).apiHisGetHisConfigGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 保存历史数据库配置
         * @param {HisConfig} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiHisUpdateHisConfigPost(body?: HisConfig, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return HisApiFp(configuration).apiHisUpdateHisConfigPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HisApi - object-oriented interface
 * @export
 * @class HisApi
 * @extends {BaseAPI}
 */
export class HisApi extends BaseAPI {
    /**
     * 
     * @summary 获取历史数据库配置
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HisApi
     */
    public async apiHisGetHisConfigGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultHisConfig>> {
        return HisApiFp(this.configuration).apiHisGetHisConfigGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 保存历史数据库配置
     * @param {HisConfig} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HisApi
     */
    public async apiHisUpdateHisConfigPost(body?: HisConfig, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return HisApiFp(this.configuration).apiHisUpdateHisConfigPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
