/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultObject } from '../models';
/**
 * SysServerApi - axios parameter creator
 * @export
 */
export const SysServerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 框架主要程序集
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysServerGetAssemblyGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysServer/getAssembly`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 服务器配置信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysServerGetServerBaseGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysServer/getServerBase`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 服务器磁盘信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysServerGetServerDiskGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysServer/getServerDisk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 服务器内存信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysServerGetServerUsedGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysServer/getServerUsed`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SysServerApi - functional programming interface
 * @export
 */
export const SysServerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 框架主要程序集
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysServerGetAssemblyGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultObject>>> {
            const localVarAxiosArgs = await SysServerApiAxiosParamCreator(configuration).apiSysServerGetAssemblyGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 服务器配置信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysServerGetServerBaseGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultObject>>> {
            const localVarAxiosArgs = await SysServerApiAxiosParamCreator(configuration).apiSysServerGetServerBaseGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 服务器磁盘信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysServerGetServerDiskGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultObject>>> {
            const localVarAxiosArgs = await SysServerApiAxiosParamCreator(configuration).apiSysServerGetServerDiskGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 服务器内存信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysServerGetServerUsedGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultObject>>> {
            const localVarAxiosArgs = await SysServerApiAxiosParamCreator(configuration).apiSysServerGetServerUsedGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SysServerApi - factory interface
 * @export
 */
export const SysServerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 框架主要程序集
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysServerGetAssemblyGet(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultObject>> {
            return SysServerApiFp(configuration).apiSysServerGetAssemblyGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 服务器配置信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysServerGetServerBaseGet(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultObject>> {
            return SysServerApiFp(configuration).apiSysServerGetServerBaseGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 服务器磁盘信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysServerGetServerDiskGet(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultObject>> {
            return SysServerApiFp(configuration).apiSysServerGetServerDiskGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 服务器内存信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysServerGetServerUsedGet(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultObject>> {
            return SysServerApiFp(configuration).apiSysServerGetServerUsedGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SysServerApi - object-oriented interface
 * @export
 * @class SysServerApi
 * @extends {BaseAPI}
 */
export class SysServerApi extends BaseAPI {
    /**
     * 
     * @summary 框架主要程序集
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysServerApi
     */
    public async apiSysServerGetAssemblyGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultObject>> {
        return SysServerApiFp(this.configuration).apiSysServerGetAssemblyGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 服务器配置信息
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysServerApi
     */
    public async apiSysServerGetServerBaseGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultObject>> {
        return SysServerApiFp(this.configuration).apiSysServerGetServerBaseGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 服务器磁盘信息
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysServerApi
     */
    public async apiSysServerGetServerDiskGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultObject>> {
        return SysServerApiFp(this.configuration).apiSysServerGetServerDiskGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 服务器内存信息
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysServerApi
     */
    public async apiSysServerGetServerUsedGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultObject>> {
        return SysServerApiFp(this.configuration).apiSysServerGetServerUsedGet(options).then((request) => request(this.axios, this.basePath));
    }
}
