/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddDriverPluginInput
 */
export interface AddDriverPluginInput {
    /**
     * 雪花Id
     * @type {number}
     * @memberof AddDriverPluginInput
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof AddDriverPluginInput
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof AddDriverPluginInput
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof AddDriverPluginInput
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof AddDriverPluginInput
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof AddDriverPluginInput
     */
    isDelete?: boolean;
    /**
     * 驱动名称
     * @type {string}
     * @memberof AddDriverPluginInput
     */
    pluginName?: string | null;
    /**
     * 驱动文件全路径
     * @type {string}
     * @memberof AddDriverPluginInput
     */
    fileName?: string | null;
}
