/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatusEnum } from './status-enum';
/**
 * 
 * @export
 * @interface AddPosInput
 */
export interface AddPosInput {
    /**
     * 雪花Id
     * @type {number}
     * @memberof AddPosInput
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof AddPosInput
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof AddPosInput
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof AddPosInput
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof AddPosInput
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof AddPosInput
     */
    isDelete?: boolean;
    /**
     * 租户Id
     * @type {number}
     * @memberof AddPosInput
     */
    tenantId?: number | null;
    /**
     * 编码
     * @type {string}
     * @memberof AddPosInput
     */
    code?: string | null;
    /**
     * 排序
     * @type {number}
     * @memberof AddPosInput
     */
    orderNo?: number;
    /**
     * 备注
     * @type {string}
     * @memberof AddPosInput
     */
    remark?: string | null;
    /**
     * 
     * @type {StatusEnum}
     * @memberof AddPosInput
     */
    status?: StatusEnum;
    /**
     * 名称
     * @type {string}
     * @memberof AddPosInput
     */
    name: string;
}
