/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SqlDbType } from './sql-db-type';
/**
 * 报警数据库配置表
 * @export
 * @interface AlarmConfig
 */
export interface AlarmConfig {
    /**
     * 雪花Id
     * @type {number}
     * @memberof AlarmConfig
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof AlarmConfig
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof AlarmConfig
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof AlarmConfig
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof AlarmConfig
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof AlarmConfig
     */
    isDelete?: boolean;
    /**
     * 
     * @type {SqlDbType}
     * @memberof AlarmConfig
     */
    dbType?: SqlDbType;
    /**
     * 链接字符串 MD5加密
     * @type {string}
     * @memberof AlarmConfig
     */
    connStr?: string | null;
    /**
     * 启用
     * @type {boolean}
     * @memberof AlarmConfig
     */
    enable?: boolean;
}
