/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlarmEnum } from './alarm-enum';
import { CoreDataType } from './core-data-type';
import { EventEnum } from './event-enum';
/**
 * 历史报警表
 * @export
 * @interface AlarmHis
 */
export interface AlarmHis {
    /**
     * 雪花Id
     * @type {number}
     * @memberof AlarmHis
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AlarmHis
     */
    variableAddress?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AlarmHis
     */
    collectTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof AlarmHis
     */
    quality?: number;
    /**
     * 
     * @type {CoreDataType}
     * @memberof AlarmHis
     */
    coreDataType?: CoreDataType;
    /**
     * 描述
     * @type {string}
     * @memberof AlarmHis
     */
    description?: string | null;
    /**
     * 变量名称
     * @type {string}
     * @memberof AlarmHis
     */
    name?: string | null;
    /**
     * 设备名称
     * @type {string}
     * @memberof AlarmHis
     */
    deviceName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlarmHis
     */
    value?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AlarmHis
     */
    changeTime?: Date;
    /**
     * 报警时间
     * @type {Date}
     * @memberof AlarmHis
     */
    variableAlarmsAlarmTime?: Date;
    /**
     * 事件时间
     * @type {Date}
     * @memberof AlarmHis
     */
    variableAlarmsEventTime?: Date;
    /**
     * 
     * @type {AlarmEnum}
     * @memberof AlarmHis
     */
    variableAlarmsAlarmType?: AlarmEnum;
    /**
     * 
     * @type {EventEnum}
     * @memberof AlarmHis
     */
    variableAlarmsEventType?: EventEnum;
    /**
     * 报警值
     * @type {string}
     * @memberof AlarmHis
     */
    variableAlarmsAlarmCode?: string | null;
    /**
     * 报警限值
     * @type {string}
     * @memberof AlarmHis
     */
    variableAlarmsAlarmLimit?: string | null;
    /**
     * 报警文本
     * @type {string}
     * @memberof AlarmHis
     */
    variableAlarmsAlarmText?: string | null;
    /**
     * 报警源IP
     * @type {string}
     * @memberof AlarmHis
     */
    variableAlarmsMachineIP?: string | null;
}
