/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomAttributeData } from './custom-attribute-data';
import { MethodInfo } from './method-info';
import { Module } from './module';
import { SecurityRuleSet } from './security-rule-set';
import { Type } from './type';
import { TypeInfo } from './type-info';
/**
 * 
 * @export
 * @interface Assembly
 */
export interface Assembly {
    /**
     * 
     * @type {Array<TypeInfo>}
     * @memberof Assembly
     */
    definedTypes?: Array<TypeInfo> | null;
    /**
     * 
     * @type {Array<Type>}
     * @memberof Assembly
     */
    exportedTypes?: Array<Type> | null;
    /**
     * 
     * @type {string}
     * @memberof Assembly
     */
    codeBase?: string | null;
    /**
     * 
     * @type {MethodInfo}
     * @memberof Assembly
     */
    entryPoint?: MethodInfo;
    /**
     * 
     * @type {string}
     * @memberof Assembly
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Assembly
     */
    imageRuntimeVersion?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Assembly
     */
    isDynamic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Assembly
     */
    location?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Assembly
     */
    reflectionOnly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Assembly
     */
    isCollectible?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Assembly
     */
    isFullyTrusted?: boolean;
    /**
     * 
     * @type {Array<CustomAttributeData>}
     * @memberof Assembly
     */
    customAttributes?: Array<CustomAttributeData> | null;
    /**
     * 
     * @type {string}
     * @memberof Assembly
     */
    escapedCodeBase?: string | null;
    /**
     * 
     * @type {Module}
     * @memberof Assembly
     */
    manifestModule?: Module;
    /**
     * 
     * @type {Array<Module>}
     * @memberof Assembly
     */
    modules?: Array<Module> | null;
    /**
     * 
     * @type {boolean}
     * @memberof Assembly
     */
    globalAssemblyCache?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Assembly
     */
    hostContext?: number;
    /**
     * 
     * @type {SecurityRuleSet}
     * @memberof Assembly
     */
    securityRuleSet?: SecurityRuleSet;
}
