/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 数据类型<br />&nbsp; Object = 0<br />&nbsp; Bcd = 1<br />&nbsp; DateTime = 2<br />&nbsp; String = 3<br />&nbsp; Bool = 4<br />&nbsp; Byte = 5<br />&nbsp; SByte = 6<br />&nbsp; Int16 = 7<br />&nbsp; UInt16 = 8<br />&nbsp; Int32 = 9<br />&nbsp; UInt32 = 10<br />&nbsp; Int64 = 11<br />&nbsp; UInt64 = 12<br />&nbsp; Float = 13<br />&nbsp; Double = 14<br />
 * @export
 * @enum {string}
 */
export enum CoreDataType {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14
}

