/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 文化程度枚举<br />&nbsp;小学 Level1 = 0<br />&nbsp;初中 Level2 = 1<br />&nbsp;高中 Level3 = 2<br />&nbsp;中专 Level4 = 3<br />&nbsp;大专 Level5 = 4<br />&nbsp;本科 Level6 = 5<br />&nbsp;硕士研究生 Level7 = 6<br />&nbsp;博士研究生 Level8 = 7<br />
 * @export
 * @enum {string}
 */
export enum CultureLevelEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7
}

