/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomAttributeTypedArgument } from './custom-attribute-typed-argument';
import { MemberInfo } from './member-info';
/**
 * 
 * @export
 * @interface CustomAttributeNamedArgument
 */
export interface CustomAttributeNamedArgument {
    /**
     * 
     * @type {MemberInfo}
     * @memberof CustomAttributeNamedArgument
     */
    memberInfo?: MemberInfo;
    /**
     * 
     * @type {CustomAttributeTypedArgument}
     * @memberof CustomAttributeNamedArgument
     */
    typedValue?: CustomAttributeTypedArgument;
    /**
     * 
     * @type {string}
     * @memberof CustomAttributeNamedArgument
     */
    memberName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CustomAttributeNamedArgument
     */
    isField?: boolean;
}
