/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeviceOnLineStatusEnum } from './device-on-line-status-enum';
/**
 * 
 * @export
 * @interface DeviceStatus
 */
export interface DeviceStatus {
    /**
     * 设备读取分包数量
     * @type {number}
     * @memberof DeviceStatus
     */
    deviceSourceVariableNum?: number;
    /**
     * 设备分包读取成功数量
     * @type {number}
     * @memberof DeviceStatus
     */
    deviceSourceVariableSuccessNum?: number;
    /**
     * 设备分包读取失败数量
     * @type {number}
     * @memberof DeviceStatus
     */
    deviceSourceVariableFailedNum?: number;
    /**
     * 设备特殊方法数量
     * @type {number}
     * @memberof DeviceStatus
     */
    deviceMedsVariableNum?: number;
    /**
     * 设备特殊方法成功数量
     * @type {number}
     * @memberof DeviceStatus
     */
    deviceMedsVariableSuccessNum?: number;
    /**
     * 设备特殊方法失败数量
     * @type {number}
     * @memberof DeviceStatus
     */
    deviceMedsVariableFailedNum?: number;
    /**
     * 设备活跃时间
     * @type {Date}
     * @memberof DeviceStatus
     */
    activeTime?: Date;
    /**
     * 
     * @type {DeviceOnLineStatusEnum}
     * @memberof DeviceStatus
     */
    deviceOnLineStatus?: DeviceOnLineStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof DeviceStatus
     */
    deviceOffMsg?: string | null;
}
