/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BCDFormat } from './bcdformat';
import { CoreDataType } from './core-data-type';
import { Device } from './device';
import { Encoding } from './encoding';
import { IThingsGatewayBitConverter } from './ithings-gateway-bit-converter';
import { ProtectTypeEnum } from './protect-type-enum';
import { Type } from './type';
import { VariableAlarm } from './variable-alarm';
import { VariableCahngeEventHandler } from './variable-cahnge-event-handler';
import { VariableHis } from './variable-his';
import { VariableProperty } from './variable-property';
/**
 * 
 * @export
 * @interface DeviceVariableCopy
 */
export interface DeviceVariableCopy {
    /**
     * 
     * @type {number}
     * @memberof DeviceVariableCopy
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof DeviceVariableCopy
     */
    createTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof DeviceVariableCopy
     */
    updateTime?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof DeviceVariableCopy
     */
    createUserId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DeviceVariableCopy
     */
    updateUserId?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof DeviceVariableCopy
     */
    isDelete?: boolean;
    /**
     * 
     * @type {IThingsGatewayBitConverter}
     * @memberof DeviceVariableCopy
     */
    thingsGatewayBitConverter?: IThingsGatewayBitConverter;
    /**
     * 
     * @type {Date}
     * @memberof DeviceVariableCopy
     */
    changeTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DeviceVariableCopy
     */
    collectTime?: Date;
    /**
     * 
     * @type {Device}
     * @memberof DeviceVariableCopy
     */
    device?: Device;
    /**
     * 
     * @type {number}
     * @memberof DeviceVariableCopy
     */
    deviceId?: number;
    /**
     * 
     * @type {string}
     * @memberof DeviceVariableCopy
     */
    deviceName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceVariableCopy
     */
    expressions?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DeviceVariableCopy
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof DeviceVariableCopy
     */
    invokeInterval?: number;
    /**
     * 
     * @type {any}
     * @memberof DeviceVariableCopy
     */
    objectTag?: any | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceVariableCopy
     */
    otherMethod?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DeviceVariableCopy
     */
    quality?: number;
    /**
     * 
     * @type {BCDFormat}
     * @memberof DeviceVariableCopy
     */
    stringBCDFormat?: BCDFormat;
    /**
     * 
     * @type {Encoding}
     * @memberof DeviceVariableCopy
     */
    stringEncoding?: Encoding;
    /**
     * 
     * @type {number}
     * @memberof DeviceVariableCopy
     */
    stringLength?: number;
    /**
     * 
     * @type {any}
     * @memberof DeviceVariableCopy
     */
    value?: any | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceVariableCopy
     */
    variableAddress?: string | null;
    /**
     * 
     * @type {VariableCahngeEventHandler}
     * @memberof DeviceVariableCopy
     */
    variableCollectChange?: VariableCahngeEventHandler;
    /**
     * 
     * @type {VariableCahngeEventHandler}
     * @memberof DeviceVariableCopy
     */
    variableCollectIntelnalChange?: VariableCahngeEventHandler;
    /**
     * 
     * @type {VariableCahngeEventHandler}
     * @memberof DeviceVariableCopy
     */
    variableValueChange?: VariableCahngeEventHandler;
    /**
     * 
     * @type {CoreDataType}
     * @memberof DeviceVariableCopy
     */
    coreDataType?: CoreDataType;
    /**
     * 
     * @type {Type}
     * @memberof DeviceVariableCopy
     */
    dataType?: Type;
    /**
     * 
     * @type {string}
     * @memberof DeviceVariableCopy
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceVariableCopy
     */
    initialValue?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceVariableCopy
     */
    name?: string | null;
    /**
     * 
     * @type {ProtectTypeEnum}
     * @memberof DeviceVariableCopy
     */
    protectType?: ProtectTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof DeviceVariableCopy
     */
    rawValue?: any | null;
    /**
     * 
     * @type {VariableAlarm}
     * @memberof DeviceVariableCopy
     */
    variableAlarms?: VariableAlarm;
    /**
     * 
     * @type {VariableHis}
     * @memberof DeviceVariableCopy
     */
    variableHiss?: VariableHis;
    /**
     * 
     * @type {VariableProperty}
     * @memberof DeviceVariableCopy
     */
    variablePropertys?: VariableProperty;
}
