/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DecoderFallback } from './decoder-fallback';
import { EncoderFallback } from './encoder-fallback';
import { ReadOnlySpanByte } from './read-only-span-byte';
/**
 * 
 * @export
 * @interface Encoding
 */
export interface Encoding {
    /**
     * 
     * @type {ReadOnlySpanByte}
     * @memberof Encoding
     */
    preamble?: ReadOnlySpanByte;
    /**
     * 
     * @type {string}
     * @memberof Encoding
     */
    bodyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Encoding
     */
    encodingName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Encoding
     */
    headerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Encoding
     */
    webName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Encoding
     */
    windowsCodePage?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Encoding
     */
    isBrowserDisplay?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Encoding
     */
    isBrowserSave?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Encoding
     */
    isMailNewsDisplay?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Encoding
     */
    isMailNewsSave?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Encoding
     */
    isSingleByte?: boolean;
    /**
     * 
     * @type {EncoderFallback}
     * @memberof Encoding
     */
    encoderFallback?: EncoderFallback;
    /**
     * 
     * @type {DecoderFallback}
     * @memberof Encoding
     */
    decoderFallback?: DecoderFallback;
    /**
     * 
     * @type {boolean}
     * @memberof Encoding
     */
    isReadOnly?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Encoding
     */
    codePage?: number;
}
