/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 报警事件类型<br />&nbsp; None = 0<br />&nbsp; Alarm = 1<br />&nbsp; Check = 2<br />&nbsp; Finish = 3<br />
 * @export
 * @enum {string}
 */
export enum EventEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}

