/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FileOutput
 */
export interface FileOutput {
    /**
     * Id
     * @type {number}
     * @memberof FileOutput
     */
    id?: number;
    /**
     * 提供者
     * @type {string}
     * @memberof FileOutput
     */
    provider?: string | null;
    /**
     * 名称
     * @type {string}
     * @memberof FileOutput
     */
    name?: string | null;
    /**
     * URL
     * @type {string}
     * @memberof FileOutput
     */
    url?: string | null;
    /**
     * 大小
     * @type {string}
     * @memberof FileOutput
     */
    sizeKb?: string | null;
    /**
     * 后缀
     * @type {string}
     * @memberof FileOutput
     */
    suffix?: string | null;
    /**
     * 路径
     * @type {string}
     * @memberof FileOutput
     */
    filePath?: string | null;
}
