/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MessageTypeEnum } from './message-type-enum';
/**
 * 
 * @export
 * @interface MessageInput
 */
export interface MessageInput {
    /**
     * 用户ID
     * @type {number}
     * @memberof MessageInput
     */
    userId?: number;
    /**
     * 用户ID列表
     * @type {Array<number>}
     * @memberof MessageInput
     */
    userIds?: Array<number> | null;
    /**
     * 消息标题
     * @type {string}
     * @memberof MessageInput
     */
    title?: string | null;
    /**
     * 
     * @type {MessageTypeEnum}
     * @memberof MessageInput
     */
    messageType?: MessageTypeEnum;
    /**
     * 消息内容
     * @type {string}
     * @memberof MessageInput
     */
    message?: string | null;
}
