/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PluginAssemble } from './plugin-assemble';
/**
 * 驱动插件信息
 * @export
 * @interface PluginInfo
 */
export interface PluginInfo {
    /**
     * 驱动文件全路径
     * @type {string}
     * @memberof PluginInfo
     */
    fileName?: string | null;
    /**
     * 插件程序集名与Type的字典
     * @type {Array<PluginAssemble>}
     * @memberof PluginInfo
     */
    pluginAssemble?: Array<PluginAssemble> | null;
    /**
     * 驱动文件名称
     * @type {string}
     * @memberof PluginInfo
     */
    pluginName?: string | null;
}
