/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PluginInfo } from './plugin-info';
/**
 * 分页泛型集合
 * @export
 * @interface SqlSugarPagedListPluginInfo
 */
export interface SqlSugarPagedListPluginInfo {
    /**
     * 页码
     * @type {number}
     * @memberof SqlSugarPagedListPluginInfo
     */
    page?: number;
    /**
     * 页容量
     * @type {number}
     * @memberof SqlSugarPagedListPluginInfo
     */
    pageSize?: number;
    /**
     * 总条数
     * @type {number}
     * @memberof SqlSugarPagedListPluginInfo
     */
    total?: number;
    /**
     * 总页数
     * @type {number}
     * @memberof SqlSugarPagedListPluginInfo
     */
    totalPages?: number;
    /**
     * 当前页集合
     * @type {Array<PluginInfo>}
     * @memberof SqlSugarPagedListPluginInfo
     */
    items?: Array<PluginInfo> | null;
    /**
     * 是否有上一页
     * @type {boolean}
     * @memberof SqlSugarPagedListPluginInfo
     */
    hasPrevPage?: boolean;
    /**
     * 是否有下一页
     * @type {boolean}
     * @memberof SqlSugarPagedListPluginInfo
     */
    hasNextPage?: boolean;
}
