/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NoticeUserStatusEnum } from './notice-user-status-enum';
import { SysNotice } from './sys-notice';
/**
 * 系统通知公告用户表
 * @export
 * @interface SysNoticeUser
 */
export interface SysNoticeUser {
    /**
     * 通知公告Id
     * @type {number}
     * @memberof SysNoticeUser
     */
    noticeId?: number;
    /**
     * 
     * @type {SysNotice}
     * @memberof SysNoticeUser
     */
    sysNotice?: SysNotice;
    /**
     * 用户Id
     * @type {number}
     * @memberof SysNoticeUser
     */
    userId?: number;
    /**
     * 阅读时间
     * @type {Date}
     * @memberof SysNoticeUser
     */
    readTime?: Date | null;
    /**
     * 
     * @type {NoticeUserStatusEnum}
     * @memberof SysNoticeUser
     */
    readStatus?: NoticeUserStatusEnum;
}
