/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeviceProperty } from './device-property';
import { DeviceStatus } from './device-status';
/**
 * 
 * @export
 * @interface UpdateDeviceInput
 */
export interface UpdateDeviceInput {
    /**
     * 雪花Id
     * @type {number}
     * @memberof UpdateDeviceInput
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof UpdateDeviceInput
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof UpdateDeviceInput
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof UpdateDeviceInput
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof UpdateDeviceInput
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof UpdateDeviceInput
     */
    isDelete?: boolean;
    /**
     * 变化上传
     * @type {boolean}
     * @memberof UpdateDeviceInput
     */
    changeUpload?: boolean;
    /**
     * 描述
     * @type {string}
     * @memberof UpdateDeviceInput
     */
    description?: string | null;
    /**
     * 驱动子程序集名称
     * @type {string}
     * @memberof UpdateDeviceInput
     */
    driverAssembleName?: string | null;
    /**
     * 设备使能
     * @type {boolean}
     * @memberof UpdateDeviceInput
     */
    invokeEnable?: boolean;
    /**
     * 默认执行间隔
     * @type {number}
     * @memberof UpdateDeviceInput
     */
    invokeInterval?: number;
    /**
     * 名称
     * @type {string}
     * @memberof UpdateDeviceInput
     */
    name?: string | null;
    /**
     * 设备属性
     * @type {Array<DeviceProperty>}
     * @memberof UpdateDeviceInput
     */
    deviceProperties?: Array<DeviceProperty> | null;
    /**
     * 设备属性数量
     * @type {number}
     * @memberof UpdateDeviceInput
     */
    devicePropertieNum?: number;
    /**
     * 设备变量数量
     * @type {number}
     * @memberof UpdateDeviceInput
     */
    deviceVariableNum?: number;
    /**
     * 
     * @type {DeviceStatus}
     * @memberof UpdateDeviceInput
     */
    deviceStatus?: DeviceStatus;
}
