/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BCDFormat } from './bcdformat';
import { CoreDataType } from './core-data-type';
import { ProtectTypeEnum } from './protect-type-enum';
import { Type } from './type';
import { VariableAlarm } from './variable-alarm';
import { VariableHis } from './variable-his';
import { VariableProperty } from './variable-property';
/**
 * 
 * @export
 * @interface UpdateDeviceVariableInput
 */
export interface UpdateDeviceVariableInput {
    /**
     * 雪花Id
     * @type {number}
     * @memberof UpdateDeviceVariableInput
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof UpdateDeviceVariableInput
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof UpdateDeviceVariableInput
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof UpdateDeviceVariableInput
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof UpdateDeviceVariableInput
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof UpdateDeviceVariableInput
     */
    isDelete?: boolean;
    /**
     * 
     * @type {CoreDataType}
     * @memberof UpdateDeviceVariableInput
     */
    coreDataType?: CoreDataType;
    /**
     * 描述
     * @type {string}
     * @memberof UpdateDeviceVariableInput
     */
    description?: string | null;
    /**
     * 初始值
     * @type {string}
     * @memberof UpdateDeviceVariableInput
     */
    initialValue?: string | null;
    /**
     * 
     * @type {ProtectTypeEnum}
     * @memberof UpdateDeviceVariableInput
     */
    protectType?: ProtectTypeEnum;
    /**
     * 变量名称
     * @type {string}
     * @memberof UpdateDeviceVariableInput
     */
    name?: string | null;
    /**
     * 
     * @type {VariableProperty}
     * @memberof UpdateDeviceVariableInput
     */
    variablePropertys?: VariableProperty;
    /**
     * 
     * @type {VariableAlarm}
     * @memberof UpdateDeviceVariableInput
     */
    variableAlarms?: VariableAlarm;
    /**
     * 
     * @type {VariableHis}
     * @memberof UpdateDeviceVariableInput
     */
    variableHiss?: VariableHis;
    /**
     * 
     * @type {Type}
     * @memberof UpdateDeviceVariableInput
     */
    dataType?: Type;
    /**
     * 原始值
     * @type {any}
     * @memberof UpdateDeviceVariableInput
     */
    rawValue?: any | null;
    /**
     * 设备名称
     * @type {number}
     * @memberof UpdateDeviceVariableInput
     */
    deviceId?: number;
    /**
     * 变量值表达式
     * @type {string}
     * @memberof UpdateDeviceVariableInput
     */
    expressions?: string | null;
    /**
     * 其他方法，若不为空，此时Address为方法参数
     * @type {string}
     * @memberof UpdateDeviceVariableInput
     */
    otherMethod?: string | null;
    /**
     * 变量地址，可能带有额外的信息，比如ThingsGateway.Foundation.DataFormat ，以;分割
     * @type {string}
     * @memberof UpdateDeviceVariableInput
     */
    variableAddress?: string | null;
    /**
     * 执行间隔，小于等于0时使用ThingsGateway.Application.Core.Device.InvokeInterval
     * @type {number}
     * @memberof UpdateDeviceVariableInput
     */
    invokeInterval?: number;
    /**
     * 
     * @type {any}
     * @memberof UpdateDeviceVariableInput
     */
    value?: any | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateDeviceVariableInput
     */
    changeTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateDeviceVariableInput
     */
    collectTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof UpdateDeviceVariableInput
     */
    quality?: number;
    /**
     * M:ThingsGateway.Application.Core.DriverBase.ReadAsync(System.String,System.UInt16)返回字节组中的索引位置              <br></br>              这个参数值由自动分包方法写入M:ThingsGateway.Application.Core.DriverBase.LoadSourceRead(System.Collections.Generic.List{ThingsGateway.Application.Core.DeviceVariable})
     * @type {number}
     * @memberof UpdateDeviceVariableInput
     */
    index?: number;
    /**
     * 变量在属于字符串类型时的字符串长度  <br></br>  这个参数值由自动分包方法写入M:ThingsGateway.Application.Core.DriverBase.LoadSourceRead(System.Collections.Generic.List{ThingsGateway.Application.Core.DeviceVariable})
     * @type {number}
     * @memberof UpdateDeviceVariableInput
     */
    stringLength?: number;
    /**
     * 
     * @type {BCDFormat}
     * @memberof UpdateDeviceVariableInput
     */
    stringBCDFormat?: BCDFormat;
}
