/* tslint:disable */
/* eslint-disable */
/**
 * ThingsGateway物联网关全部接口
 * 作者By Diego,QQ2248356998 框架系统参考或集成以下开源系统，在此感谢！<br/> <a href='https://gitee.com/zuohuaijun/Admin.NET/'>Admin.NET</a><br/> <a href='https://gitee.com/dotnetchina/TouchSocket'>TouchSocket</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2248356998@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlarmEnum } from './alarm-enum';
import { EventEnum } from './event-enum';
/**
 * 变量报警属性表
 * @export
 * @interface VariableAlarm
 */
export interface VariableAlarm {
    /**
     * 雪花Id
     * @type {number}
     * @memberof VariableAlarm
     */
    id?: number;
    /**
     * 报警组
     * @type {string}
     * @memberof VariableAlarm
     */
    alarmGroup?: string | null;
    /**
     * 报警死区
     * @type {number}
     * @memberof VariableAlarm
     */
    alarmDeadZone?: number;
    /**
     * 报警延时
     * @type {number}
     * @memberof VariableAlarm
     */
    alarmDelayTime?: number;
    /**
     * 布尔开报警使能
     * @type {boolean}
     * @memberof VariableAlarm
     */
    boolOpenAlarmEnable?: boolean;
    /**
     * 布尔开报警约束
     * @type {string}
     * @memberof VariableAlarm
     */
    boolOpenRestrainExpressions?: string | null;
    /**
     * 布尔开报警文本
     * @type {string}
     * @memberof VariableAlarm
     */
    boolOpenAlarmText?: string | null;
    /**
     * 布尔关报警使能
     * @type {boolean}
     * @memberof VariableAlarm
     */
    boolCloseAlarmEnable?: boolean;
    /**
     * 布尔关报警约束
     * @type {string}
     * @memberof VariableAlarm
     */
    boolCloseRestrainExpressions?: string | null;
    /**
     * 布尔关报警文本
     * @type {string}
     * @memberof VariableAlarm
     */
    boolCloseAlarmText?: string | null;
    /**
     * 高报使能
     * @type {boolean}
     * @memberof VariableAlarm
     */
    hAlarmEnable?: boolean;
    /**
     * 高报约束
     * @type {string}
     * @memberof VariableAlarm
     */
    hRestrainExpressions?: string | null;
    /**
     * 高报文本
     * @type {string}
     * @memberof VariableAlarm
     */
    hAlarmText?: string | null;
    /**
     * 高限值
     * @type {number}
     * @memberof VariableAlarm
     */
    hAlarmCode?: number;
    /**
     * 高高报使能
     * @type {boolean}
     * @memberof VariableAlarm
     */
    hhAlarmEnable?: boolean;
    /**
     * 高高报约束
     * @type {string}
     * @memberof VariableAlarm
     */
    hhRestrainExpressions?: string | null;
    /**
     * 高高报文本
     * @type {string}
     * @memberof VariableAlarm
     */
    hhAlarmText?: string | null;
    /**
     * 高高限值
     * @type {number}
     * @memberof VariableAlarm
     */
    hhAlarmCode?: number;
    /**
     * 低报使能
     * @type {boolean}
     * @memberof VariableAlarm
     */
    lAlarmEnable?: boolean;
    /**
     * 低报约束
     * @type {string}
     * @memberof VariableAlarm
     */
    lRestrainExpressions?: string | null;
    /**
     * 低报文本
     * @type {string}
     * @memberof VariableAlarm
     */
    lAlarmText?: string | null;
    /**
     * 低限值
     * @type {number}
     * @memberof VariableAlarm
     */
    lAlarmCode?: number;
    /**
     * 低低报使能
     * @type {boolean}
     * @memberof VariableAlarm
     */
    llAlarmEnable?: boolean;
    /**
     * 低低报约束
     * @type {string}
     * @memberof VariableAlarm
     */
    llRestrainExpressions?: string | null;
    /**
     * 低低报文本
     * @type {string}
     * @memberof VariableAlarm
     */
    llAlarmText?: string | null;
    /**
     * 低低限值
     * @type {number}
     * @memberof VariableAlarm
     */
    llAlarmCode?: number;
    /**
     * 变量Id
     * @type {number}
     * @memberof VariableAlarm
     */
    variableId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof VariableAlarm
     */
    alarmEnable?: boolean;
    /**
     * 报警时间
     * @type {Date}
     * @memberof VariableAlarm
     */
    alarmTime?: Date;
    /**
     * 事件时间
     * @type {Date}
     * @memberof VariableAlarm
     */
    eventTime?: Date;
    /**
     * 
     * @type {AlarmEnum}
     * @memberof VariableAlarm
     */
    alarmType?: AlarmEnum;
    /**
     * 
     * @type {EventEnum}
     * @memberof VariableAlarm
     */
    eventType?: EventEnum;
    /**
     * 报警值
     * @type {any}
     * @memberof VariableAlarm
     */
    alarmCode?: any | null;
    /**
     * 报警限值
     * @type {any}
     * @memberof VariableAlarm
     */
    alarmLimit?: any | null;
    /**
     * 报警文本
     * @type {string}
     * @memberof VariableAlarm
     */
    alarmText?: string | null;
    /**
     * 报警源IP
     * @type {string}
     * @memberof VariableAlarm
     */
    machineIP?: string | null;
}
